### ISSUE TITLE
Can ReferenceField be implemented some way?

### ISSUE THREAD

**Issue by wonderbeyond** [threatify/arango-orm#11]
Like [MongoEngine's ReferenceField](http://docs.mongoengine.org/apireference.html#mongoengine.fields.ReferenceField).

**Comment by kashifpk** [comment]
@wonderbeyond sure, that's a nice idea. I assume it can be similar to SQLAlchemy's relationship attribute for model classes and could take in the document ID.

I was away so couldn't get back to it earlier. Have you started implementing this? I

**Comment by wonderbeyond** [comment]
@kashifpk not yet. I've not a good idea for implementing it.

**Comment by wonderbeyond** [comment]
I'm trying, but it's too difficult.

Assume the below use case:

```python
class Case(Collection):
    class _Schema(Schema):
        _key = String()
        title = String()

class Task(Collection):
    class _Schema(Schema):
        _key = String()
        case = ReferenceField(Case)
```

I'm trying a ReferenceField like this:

```python
import six
from marshmallow.fields import Nested


class ReferenceField(Nested):
    def __init__(self, model, **kwargs):
        self.model = model
        return super(ReferenceField, self).__init__(model._Schema, **kwargs)

    def _deserialize(self, value, attr, data):
        if isinstance(value, six.string_types):
            # I'll load a ref model's data by _key,
            # But how to get the current db object?
            # And can I inspect it from current object(or its field),
            # Like http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#how-can-i-get-the-session-for-a-certain-object
            value = {
                'title': 'Fake Case'
            }
        return super(ReferenceField, self)._deserialize(value, attr, data)
```

Please note the comments in `_deserialize` method.

**Comment by kashifpk** [comment]
Remember arango is also a graph database and that part is ideal for relationships. Typically where you have foreign keys and linkages to other tables, in arango you would need to place a relation collection in between the two collections that need to be linked.

And we have graph expansion supported to get the linked data. Consider the example::
```python

    class Domain(Collection):
        __collection__ = 'domains'

        class _Schema(Schema):
            _key = String(required=True)  # The domain name

    class IPAddress(Collection):
    
        __collection__ = 'ip_addresses'
    
        _index = [
            {"type": "geo", "fields": ["geo_location"]}
        ]
    
        class _Schema(Schema):
            _key = String(required=True)  # the actual ip address
            ip_version = Integer(required=True, options=[4, 6])
            geo_location = List(Float())

    class HasAddress(Relation):
    
        __collection__ = 'has_address'
    
        class _Schema(Schema):
            _from = String(required=True)   # The domain name
            _to = String(required=True)   # The ip address
            _source = List(String())

    class MyGraph(Graph):
    
        __graph__ = 'my_graph'
    
        graph_connections = [
            GraphConnection(Domain, HasAddress, IPAddress)
        ]
```

With this kind of setup we can get a record and expand it from the graph and get all linked documents in the _relations attribute. This already works. For ReferenceField we can build upon that. Instead of trying to access the database object in the schema or class, we resolve reference fields in the Query.

Let's say we modify the Domain class to include reference field:

```python
    class Domain(Collection):
        __collection__ = 'domains'

        class _Schema(Schema):
            _key = String(required=True)  # The domain name

        ip_addresses = ReferenceField(HasAddress)
```

When the query method is called and it gets a document back, it would do something like:
1. See if the object contains any field of type ReferenceField.
2. Check in which graph the collection resides in, instantiate a graph instance and expand the record
3. Fetch the linked data from the Relation collection referenced in the ReferenceField 

I have been thinking about this and have most of this sorted out but still need to think through a few other things before implementing it.

In the meanwhile, we can still get referenced data like:

```python
G = MyGraph(connection=db)
domain = db.query(Domain).by_key('acme.org')
G.expand(domain, depth=1)
domain_ips = [ rel_doc._next._key  for rel_doc in domain._relations['has_address'] ]
```

When we implement ReferenceField, it would basically do something similar but that would be done inside the ORM and then we would simply assign that to a record property, something like:

```python
domain.ip_addresses = [ rel_doc._next  for rel_doc in domain._relations['has_address'] ]
for ip_doc in domain.ip_addresses:
     print(ip_doc._key)
```

Hope this makes sense :-)

**Comment by wonderbeyond** [comment]
@kashifpk Thank you for the long reply.

Graph mode is capable for expressing any kind of relations.
However, after some discussion and thought we chose not using it for **typical relationship model**(e.g. 1-N, M-M).
I think graph is specially for expressing relations with complex or uncertain depth.

For typical relationship, A Foreignkey(or array of Foreignkeys) field on an real(non-edge) document is more concise.
It uses less code for defining the schema, and maybe more efficient for DB querying.

---

According to [ArangoDB Docs](https://docs.arangodb.com/3.1/cookbook/AQL/Joins.html), ArangoDB does support joins for **One-To-Many** and **Many-To-Many** without edges. And no words saying edge/graph is better way for these kind of relationships.
