### ISSUE TITLE
Shall we switch to first-class schema definition?

### ISSUE THREAD

**Issue by wonderbeyond** [threatify/arango-orm#17]
Currently our schema is defined as subclass of `marshmallow.Schema`, separated from the model class itself. It's easy for implementation in some way but inconvenient many times.

- When saved into db, we simply use the `dump` result. however `dump` is better for front-end or cross-platform exchange, not the same as DB.
- It's almost not able declare a db-specific field options on Marshmallow fields.
- We cannot use model mixins or inheritance without first-class schema definition.
- ...

---

Below is just a code sample from a project using Mezzanine(A Django-based CMS System):
```python
class Article(Displayable, Ownable, RichText, AdminThumbMixin):
    category = models.ForeignKey("Category", verbose_name="Category")
    featured_image = FileField(
        verbose_name=_("Featured Image"),
        upload_to=upload_to("news.Article.featured_image", "news"),
        format="Image",
        max_length=255,
        null=True,
        blank=True
    )
    location = models.CharField(max_length=200, null=True, blank=True)

    admin_thumb_field = "featured_image"

    class Meta:
        ordering = ("-publish_date", )

    def get_absolute_url(self):
        return reverse('article-detail', kwargs={'slug': self.slug})
```

**Comment by kashifpk** [comment]
@wonderbeyond you raise valid points. I guess we could allow setting class properties directly instead of inside the Schema child class. For validation etc we could do that within the Collection class itself. I'd need to think a bit more into it to see how to design and implement it. Thank you for your input :-)

**Comment by wonderbeyond** [comment]
Shall we go django-style or sqlalchemy-style?

**Comment by kashifpk** [comment]
Well the rest is influenced by sqlalchemy so we should try to stick to that

**Comment by kashifpk** [comment]
@wonderbeyond I've updated the collection definition to look similar to SQLAlchemy model definition. For example:

```python
from marshmallow.fields import String, Date


class Person(Collection):

    __collection__ = 'persons'
    _index = [{'type': 'hash', 'unique': False, 'fields': ['name']}]

    _key = String(required=True)
    name = String(required=True, allow_none=False)
    dob = Date()

    def __str__(self):
        return "<Person(" + self.name + ")>"

```

Hope now you can inherit attributes from parent models. Looks better too.

**Comment by kashifpk** [comment]
@wonderbeyond The updates for #21 have caused some issues with this. We can no longer inherit schema attributes from parent class into a child class. Consider the following scenario

```python
from arango_orm.fields import String, DateTime, Dict
from arango_orm import Collection

class ResultMixin(object):
    _key = String()
    _timestamp = DateTime()

class PingResult(ResultMixin, Collection):
    __collection__ = "ping_results"
    host = String(required=True)
    status = String(required=True)   # UP, DOWN, SLOW
    error_message = String()
    stats = Dict()

# schema only generates fields present in the current class and does not inherit fields from parent classes
PingResult.schema().fields.keys()
=> dict_keys(['stats', 'status', 'error_message', 'host'])
```

I should have added test cases for these so that it could have been identified earlier. Do you have any ideas what might be causing this? I think that issue is with CollectionMeta.__new__ on 
https://github.com/threatify/arango-orm/blob/master/arango_orm/collections.py#L20 and https://github.com/threatify/arango-orm/blob/master/arango_orm/collections.py#L29

Seems like we're not considering the attrs of base classes.

**Comment by kashifpk** [comment]
I see you're using _fields to store the field names for the schema? If yes, then it should be merge with parent class _fields attributes if present?

**Comment by kashifpk** [comment]
@wonderbeyond nvm, fixed :-)

**Comment by wonderbeyond** [comment]
@kashifpk 

I've considered this issue, However I didn't mention it since collection inheritance is not an existing feature.

With my previous commit, collection inheritance is possible, but the Mixin itself should also inherit `CollectionBase` class, like below:

```python
from arango_orm import CollectionBase, Collection
from arango_orm.fields import String, Dict, DateTime

class ResultMixin(CollectionBase):
    _key = String()
    _timestamp = DateTime()
    stats = String()

class PingResult(ResultMixin, Collection):
    __collection__ = "ping_results"
    host = String(required=True)
    status = String(required=True)   # UP, DOWN, SLOW
    error_message = String()
    stats = Dict()

'''
>>> PingResult.schema().fields.keys()
['status', '_timestamp', 'stats', '_key', 'error_message', 'host']
'''
```

However, I'm very sorry that **I just now found a bug in my previous commit, which prevents this feature**.

I've fixed that bug, and added a test case for collection mixin/inheritance.

**Comment by wonderbeyond** [comment]
@kashifpk I have not posted a PR, since you have tried your own way to fix this problem.

You can review my solution first and then make a decision.

**Comment by kashifpk** [comment]
@wonderbeyond please post a PR because your solution seems more elegant. Do you think it will have any issues with multi-layer inheritance? Let's say Collection class C is inherited from collection class B which inherits from collection class A, A->B->C, would in this case C will have all fields from A and B?

**Comment by wonderbeyond** [comment]
@kashifpk multi-layer inheritance would be OK since I always merge `new_fields` into super class' `_fields`, which travels base classes with respect to the MRO rule.

However, a test case is required to prove. I have no time for coding today.
