### ISSUE TITLE
How does .all() work with Relations?

### ISSUE THREAD

**Issue by anpr** [threatify/arango-orm#25]
I have code along the lines of

```
# testdb is an arango-orm Database instance
# MyRelation inherits from Relation
items = testdb.query(MyRelation).all()
```

This used to work with arango-orm 0.2.2, but does *not* anymore with 0.2.3.

The reason seems to be that the signature of `Collection.load()` changed recently (with https://github.com/threatify/arango-orm/commit/60a5ee82046b2eda2997d55a0bae080f20422fd1), but the signature of `Relation.load()` did not. The former now takes an additional `db` parameter. Because `Query#all()` calls `_load` with its `db` argument, it doesn't work for relations anymore. 

Is that intended? If yes, how can you call `.all()` for Relations?

**Comment by kashifpk** [comment]
@anpr - This was not intentional but rather the Relation._load method lagged behind while improvements were being made to Collection._load.

The last commit
https://github.com/threatify/arango-orm/commit/0fba3918a2d0538da58401a08eff7ee75792b136

fixes this so if you checkout code from github this issue should go away. The next released version will also have this fixed after some refactoring and test cases for this issue.

Thank you for pointing it out :-)

**Comment by anpr** [comment]
Thank you!
