### ISSUE TITLE
[Draft] Decouple from marshmallow?

### ISSUE THREAD

**Issue by wonderbeyond** [threatify/arango-orm#32]
[marshmallow](https://marshmallow.readthedocs.io/en/latest/) is mainly for **serialization** and **deserialization**:

- **Deserialize** input data to app-level objects.
- **Serialize** app-level objects to primitive Python types. The serialized objects can then be rendered to standard formats such as JSON for use in an HTTP API.

**ORM/ODM** is bridge between DB and App logic:

```
+-----------------------------+                    +------------------+                  +----------+                          
|                             |                    |                  |                  |          |                          
| Front-end / External System +<------------------>+ Python Datetypes +<---------------->+ Database |                          
|                             |    Marshmallow     |                  |       ORM        |          |                          
+-----------------------------+  (Data Exchange)   +------------------+                  +----------+                                                                                                                  
```

They have different concerns. And I feel marshmallow only shares about 60% similarities with ORM.

- marshmallow have no field-options specifically for interaction with database
- I currently use the same method(`dump`) for exposing data to client and saving to DB. These are two different scenarios, but affected by same set field-options, which often leads unexpected bugs for me.
- Some options for `marshmallow.Field` have no sense as ORM, or have different semantics.
  * `marshmallow.Field.dump_only`: the doc says it like "read-only", but arango-orm just use the dump result for writing DB. `marshmallow.Field.load_only` has the similar issue.
  * `Field.default` shouldn't take effect when get `NULL` from DB explicitly. It should only have effect while saving into DB without the field.

**Comment by kashifpk** [comment]
@wonderbeyond When I started this project I used marshmallow to give me ready-to-use serialization capabilities. It was meant to speed up initial working version of the ORM. We could let go of marshmallow but then we'd have to implement our own set of classes for serialization.

Do you have any specific architecture in mind on how we should proceed? As it is now, although we can work without marshmallow, that effort doesn't seem to provide much benefits to me except for the decoupling. On the other hand skipping marshmallow won't require that much effort too.

**Comment by kashifpk** [comment]
jsonschema based validation was introduced in arango 3.7.1 
[https://www.arangodb.com/docs/stable/data-modeling-documents-schema-validation.html](https://www.arangodb.com/docs/stable/data-modeling-documents-schema-validation.html)

This might be a better alternative to using marshmallow for serialization. Since jsonschema based validation is baked into arango now, this does seem to be the better way to proceed.

**Comment by rpocase** [comment]
Just wanted to drop a use case that may not be supportable by raw arango schema. Consider an Collection that looks like:

```
class MyCollection(Collection):
    my_field =  Tuple(
        [String(required=True, allow_none=True), Dict(default={})],
        allow_none=True,
    )
```

This allows you to model some data types that arango doesn't necessarily support (in this case, a Tuple). When you go to save or load the object, my_field must be a empty list or a list with two elements (a string and a dict). You can go even further than this and enforce an object be a List  of Tuples with such construct. Marshmallow will persist the structure as a tuple even though it is stored in arangodb as an array.

Any migration away from marshmallow would break such use cases that are inherently baked into the types by arangodb does not understand. That isn't necessarily a reason notto do this, but it seems like there needs to be a compelling reason to move away from marshmallow (other than not relying on an external lib). I'm fairly confident arango's schema support should support similar constraints, but you wouldn't necessarily get free conversion to a specific type (e.g., you would get `List[Union[Str, Dict[...]]` instead of `Tuple[Union[Str, Dict[]]`.)

**Comment by kashifpk** [comment]
Yes looks like such use cases would require additional work to be handled properly in jsonschema based solutions. Going to keep this issue open for further feedback and postpone using jsonschema until we have a decision based on merits and demerits of each approach.

**Comment by rpocase** [comment]
> Merits of jsonschema

The biggest boon I can think of here is to possibly enable migration generation from arango-orm. If the schema is stored in arangoschema, it would be relatively straightforward (to things I can think of today with the current setup) to diff the local schema and remote schema, generate a set of migrations to bring existing items in line with that schema, and the queries provided by the migrations. 

There are certainly many cases where simply having arangoschema wouldn't help (e.g. I recently moved an edge relationship to be stored as a reference field), but some basic "make sure documents in this collection have this field set" migrations could be immensely valuable.
