### ISSUE TITLE
Add support for python-arango 4.0.0

### ISSUE THREAD

**Issue by soderluk** [threatify/arango-orm#41]
As of python-arango 4.0.0 the database constructor takes another mandatory parameter, `executor`. There's also a lot of changes in the newest version of python-arango.

Also, a note on version compatibility could be added to the readme.

**Comment by kashifpk** [comment]
@soderluk - in python arango 4.0 the ArangoClient does not accept username and password, rather it's passed to the client.db method. This has already been updated in https://github.com/threatify/arango-orm/commit/f6c4cb31162bfa74fe2030b34736a2c9438deda0.

Apart from that I'm not aware of any breaking changes and have python-arango 4.1 running with arango-orm without any issues.

The issue was that the pypi repo was not updated and still had arango-orm version 0.3. I've uploaded the latest version so now you should be able to use it with new python-arango version by just doing

```bash
pip install arango-orm
```
