### ISSUE TITLE
0.7.0 release

### ISSUE THREAD

**Issue by rpocase** [threatify/arango-orm#85]
There are quite a few features in master that would be good to have in a versioned release (e.g. `bulk_add`, `bulk_update`). Any chance of a stable release near term?

**Comment by kashifpk** [comment]
That is a good suggestion actually. I'll spend some time on documenting stuff and a few more tests and then do a release.

**Comment by Elexy** [comment]
@kashifpk just discovered your library and I like @rpocase 's suggestion. Anything I can do to help expedite a release?

**Comment by kashifpk** [comment]
We can expect a release later this month. We'll have documentation on github.io instead of the current README. @Elexy help is always welcome. For documentation I was planning to have separate pages for different features and also a recipes section to elaborate how to do common tasks. You can take a look at current pending issues or contribute with documentation (it uses sphinx and restructured text).
