### ISSUE TITLE
Allow bypassing schema validation

### ISSUE THREAD

**Issue by rpocase** [threatify/arango-orm#89]
In some cases I experiment with queries using manually crafted data (e.g. in the web interface) that may not be compatible with my arango-orm schema. This is great for a getting a since of how certain query operations work when working in the web view. When dropping to the ORM to see if it supports the type of query I need, I'd like the ability to disable schema validation to see if I'll have to do full AQL building myself.

**Comment by kashifpk** [comment]
This is only for when querying the data or also for saving?

**Comment by kashifpk** [comment]
The `_allow_extra_fields` class attribute already has this effect.

```python
from arango_orm import Collection
class Test(Collection):
    __collection__ = 'test'
    _allow_extra_fields = True
d = {'name': 'ABC', 'age': 66}
t = Test._load(d)
t.name
t.age
```

**Comment by rpocase** [comment]
`_allow_extra_fields` doesn't quite accomplish what I would be after. E.g., if `Test` above had any required fields (that weren't the fields you provided), it would correctly result in a validation error. I would expect something more like `Database(connection, permissive_schema=False)`. This would allow me to instantiate a connection that has validation enforcement disabled. This would let me do some amount of exploratory work without creating models that have no schema.

**Comment by kashifpk** [comment]
@rpocase - Future plan is to move away from marshmallow and use jsonschema since it is now provided with arango. See #32. AFAIK jsonschema based validation is enabled or disabled at collection level and not at the connection level. So we might provide a mechanism to disable/enable validation with the collection class later but that would be for all connections accessing the collection not just the current connection. 

I'm open to better solutions if you or someone else can suggest those.
